# specify directories
# FINAL synced output directory of the preprocessing pipeline. 
# Has the preprocessed reads {sample}_1.fq.gz, {sample}_2.fq.gz, {sample}_orphans.fq.gz
preprocessing_directory: '/labs/asbhatt/dmaghini/projects/benchmarking/Benchmarking/RNA/01_rrna/aggregate'
output_directory: '04_sourmash'
